services:
  escola_postgres:
    image: postgres:16
    container_name: escola_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5435"